### PR TITLE
updated to compile on latest node version

### PR DESCRIPTION
**Pull request by duralog**
hey guys... we have updated the library to compile on the latest version of node (using node-gyp). it should be backwards compatible with at least 0.8.x as well. a few things:

when I went to push the code to github, I had to do a bunch of strange merging -- I don't really know why. there was also some whitespace mixing funkiness in the the node_sigar.cc file, which I converted to tab format (I use 2-space), which could be one of the reasons why it thinks I basically rewrote the whole file.

I changed the API a bit as well and simplified some of the C++ with v8u (no performance degradation). I force the module to be invoked via the `init` method and moved some of the functions, which did not require an instance of sigar to be used, up to the main exports.

I intend to continue working on more documentation and expand the javascript API to make it easier to use. I want to also upload node based system monitor, but I need to work on other things now, so I leave you with what I have done so far.

cheers

### CODE REVIEW

**Comment by duralog** [comment]
if you'd like I can remove my repository, and rebranch and apply the changes and resubmit the PR... this is a horribly ugly changelog... I seriously don't know what went wrong. I also noticed an error with node 0.6.x where memcpy isn't defined when compiling node_sigar_utils.cc ... that can be fixed as well (even though the affected function isn't even working to begin with, lol)

peace guys

**Comment by wdavidw** [comment]
Right, sth strange in the commit history, doesn't matter. I just applied the changes, they seems good. By the way, what do u think about including sugar in the module, the recommandation stipulates the contrary (sigar must be installed separately on the system) but it seems more appropropriate to me to have it with the module. That way it's easier for the user and we dont depend on installed version.

**Comment by duralog** [comment]
I'm actually writing that code right now... I just opened github to take a look. gimme a few hours. I might need to sleep a bit... it is 10am now :) btw, there is a huge bug. I didn't update the index.js. this is the new index.js format I'm working on now:

sigar = require('sigar');
- sigar.version() <-- gonna change this over to a getter
- sigar.init() <--- normal API
- new sigar.CPUsage(ms = 1000, avgsamples = 1)

the last one is the next PR I will give in a moment. what it does, is it abstracts the samples/cpu_usage.ls code into the API. essentially, if one invokes it with (100, 1) it will return an eventemitter which emits an event every 100ms with the current cpu usage. if you invoke it with (1000, 60), it will emit an event every 1000ms with the cpu time averaged out over 1 minute.

I will be using more of this library's functionality in the future to create a full system monitor, but for now, the current implementation is just an attiny which sends functions over radio to an arduino with a light display, which shines lights for cpu usage, and email/facebook notifications.

https://github.com/danielesteban/ArduinoTalk/blob/master/ArduinoTalk.js

**Comment by duralog** [comment]
I think I misunderstood you in your last comment, by including sugar you mean, instead of a submodule, just adding the code directly???

I think that's a better idea, actually, because there are some functions that I want to remove, such as password and some formatting stuff, which is overlap to normal node functions. :+1: for just moving that code in directly. if they ever update the library (it's been over a year inactive), I'll merge the changes. I've seen some people on the forums claiming to have problems with arm processors not displaying cpuinfo correctly - which I'll look into as soon as I get the RPi out again

**Comment by wdavidw** [comment]
There are 3 options:
- submodule
- include the source code (the one mentioned in your previous email)
- let the final user install sigar on the host machine (what I really meant)
  I remember to read that the last one is generally recommanded that while writing nodejs binding, we should not include the original library but instead let the user install it with a package manager (apt-get, yum..) or manually (make).
  However, I think your idea of packaging our own fork of sigar is a possibility if you plan to invest time in it to improve it. In such case, 2 options: we include the source code or we reference through gitmodule a fork that you manage. I'm open to all scenario.
  By the way, I cant compile sigar on my osx laptop at the moment. Seems like the instructions I left on the readme no longer apply to my environment. I need some time to digg it, hopefully in the next few days.

**Comment by duralog** [comment]
hi, sorry I have been offline the last little bit. been trying to get this code out the door and haven't had time to work on much else at the moment.

I'm pretty sure I'm going to just include the library inside of the bindings. the reasons being that 1. I'd like to improve a few things and 2. I would like to compile the whole thing with gyp. I will get to this code soon. got other stuff coming out soon :) soon for the updates...

peace bro!

**Pull request merged**
